"""Background supervisor for ARPHE_WINDOWS_BRIDGE_RUNTIME_V1 (PC_SEGRETERIA)."""

from __future__ import annotations

import argparse
import ctypes
from ctypes import wintypes
import json
import logging
from logging.handlers import RotatingFileHandler
import os
from pathlib import Path
import re
import signal
import subprocess
import sys
import tempfile
import threading
import time
from typing import Any

from health import check_ready
from secret_store import load_secret


RUNTIME_ID = "ARPHE_WINDOWS_BRIDGE_RUNTIME_V1"
WORKSTATION_ID = "PC_SEGRETERIA"
CREATE_NO_WINDOW = 0x08000000
ERROR_ALREADY_EXISTS = 183
JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE = 0x00002000
JobObjectExtendedLimitInformation = 9


def expand_path(value: str) -> Path:
    return Path(os.path.expandvars(value)).expanduser().resolve()


def load_config(path: Path) -> dict[str, Any]:
    # Windows PowerShell 5.1 writes a UTF-8 BOM for ``-Encoding utf8``.
    # Accept it so configurations generated by either Windows PowerShell or
    # PowerShell 7 behave identically.
    config = json.loads(path.read_text(encoding="utf-8-sig"))
    required = ("runtime_id", "workstation_id", "tunnel_id", "tunnel_client_path", "mcp_command",
                "ready_url", "log_dir", "secret_path", "state_path", "stop_request_path")
    missing = [key for key in required if not config.get(key)]
    if missing:
        raise ValueError("Missing config values: " + ", ".join(missing))
    if config["runtime_id"] != RUNTIME_ID or config["workstation_id"] != WORKSTATION_ID:
        raise ValueError(f"This build is restricted to {RUNTIME_ID} on {WORKSTATION_ID}")
    if config["ready_url"] != "http://127.0.0.1:8080/readyz":
        raise ValueError("ready_url must be exactly http://127.0.0.1:8080/readyz")
    client = expand_path(config["tunnel_client_path"])
    if not client.is_file():
        raise FileNotFoundError(f"Tunnel client not found: {client}")
    config["tunnel_client_path"] = str(client)
    for key in ("log_dir", "secret_path", "state_path", "stop_request_path"):
        config[key] = str(expand_path(config[key]))
    return config


class SecretRedactor(logging.Filter):
    _patterns = (
        re.compile(r"(?i)(CONTROL_PLANE_API_KEY\s*[=:]\s*)\S+"),
        re.compile(r"(?i)(authorization\s*:\s*bearer\s+)\S+"),
        re.compile(r"(?i)(api[_ -]?key\s*[=:]\s*)\S+"),
        re.compile(r"\bsk-[A-Za-z0-9_-]{12,}\b"),
    )

    def __init__(self, secret: str = "") -> None:
        super().__init__()
        self.secret = secret

    def redact(self, value: str) -> str:
        if self.secret:
            value = value.replace(self.secret, "[REDACTED]")
        for pattern in self._patterns:
            value = pattern.sub(lambda match: (match.group(1) if match.lastindex else "") + "[REDACTED]", value)
        return value

    def filter(self, record: logging.LogRecord) -> bool:
        record.msg = self.redact(str(record.getMessage()))
        record.args = ()
        return True


def configure_logging(log_dir: Path, secret: str) -> tuple[logging.Logger, SecretRedactor]:
    log_dir.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger(RUNTIME_ID)
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    handler = RotatingFileHandler(log_dir / "runtime.log", maxBytes=2_000_000, backupCount=5, encoding="utf-8")
    redactor = SecretRedactor(secret)
    handler.addFilter(redactor)
    handler.setFormatter(logging.Formatter("%(asctime)sZ %(levelname)s %(message)s", "%Y-%m-%dT%H:%M:%S"))
    logger.addHandler(handler)
    logger.propagate = False
    return logger, redactor


def atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent), text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


class WindowsJob:
    def __init__(self) -> None:
        self.handle = None
        if os.name != "nt":
            return
        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        self._kernel32 = kernel32
        kernel32.CreateJobObjectW.restype = wintypes.HANDLE
        kernel32.CreateJobObjectW.argtypes = (ctypes.c_void_p, wintypes.LPCWSTR)
        kernel32.SetInformationJobObject.restype = wintypes.BOOL
        kernel32.SetInformationJobObject.argtypes = (wintypes.HANDLE, ctypes.c_int, ctypes.c_void_p, wintypes.DWORD)
        kernel32.AssignProcessToJobObject.restype = wintypes.BOOL
        kernel32.AssignProcessToJobObject.argtypes = (wintypes.HANDLE, wintypes.HANDLE)
        kernel32.CloseHandle.restype = wintypes.BOOL
        kernel32.CloseHandle.argtypes = (wintypes.HANDLE,)
        kernel32.TerminateJobObject.restype = wintypes.BOOL
        kernel32.TerminateJobObject.argtypes = (wintypes.HANDLE, wintypes.UINT)
        self.handle = kernel32.CreateJobObjectW(None, None)
        if not self.handle:
            raise ctypes.WinError(ctypes.get_last_error())

        class IO_COUNTERS(ctypes.Structure):
            _fields_ = [(name, ctypes.c_ulonglong) for name in (
                "ReadOperationCount", "WriteOperationCount", "OtherOperationCount",
                "ReadTransferCount", "WriteTransferCount", "OtherTransferCount")]

        class BASIC_LIMIT(ctypes.Structure):
            _fields_ = [("PerProcessUserTimeLimit", ctypes.c_longlong), ("PerJobUserTimeLimit", ctypes.c_longlong),
                        ("LimitFlags", wintypes.DWORD), ("MinimumWorkingSetSize", ctypes.c_size_t),
                        ("MaximumWorkingSetSize", ctypes.c_size_t), ("ActiveProcessLimit", wintypes.DWORD),
                        ("Affinity", ctypes.c_size_t), ("PriorityClass", wintypes.DWORD),
                        ("SchedulingClass", wintypes.DWORD)]

        class EXTENDED_LIMIT(ctypes.Structure):
            _fields_ = [("BasicLimitInformation", BASIC_LIMIT), ("IoInfo", IO_COUNTERS),
                        ("ProcessMemoryLimit", ctypes.c_size_t), ("JobMemoryLimit", ctypes.c_size_t),
                        ("PeakProcessMemoryUsed", ctypes.c_size_t), ("PeakJobMemoryUsed", ctypes.c_size_t)]

        info = EXTENDED_LIMIT()
        info.BasicLimitInformation.LimitFlags = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE
        if not kernel32.SetInformationJobObject(self.handle, JobObjectExtendedLimitInformation,
                                                ctypes.byref(info), ctypes.sizeof(info)):
            self.close()
            raise ctypes.WinError(ctypes.get_last_error())

    def assign(self, process: subprocess.Popen[str]) -> None:
        if self.handle and not self._kernel32.AssignProcessToJobObject(self.handle, wintypes.HANDLE(process._handle)):
            raise ctypes.WinError(ctypes.get_last_error())

    def close(self) -> None:
        if self.handle:
            self._kernel32.CloseHandle(self.handle)
            self.handle = None

    def terminate(self, exit_code: int = 1) -> None:
        if self.handle:
            self._kernel32.TerminateJobObject(self.handle, exit_code)


def acquire_single_instance() -> object:
    if os.name != "nt":
        return object()
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel32.CreateMutexW.restype = wintypes.HANDLE
    kernel32.CreateMutexW.argtypes = (ctypes.c_void_p, wintypes.BOOL, wintypes.LPCWSTR)
    kernel32.CloseHandle.restype = wintypes.BOOL
    kernel32.CloseHandle.argtypes = (wintypes.HANDLE,)
    ctypes.set_last_error(0)
    handle = kernel32.CreateMutexW(None, False, f"Local\\{RUNTIME_ID}_{WORKSTATION_ID}")
    if not handle:
        raise ctypes.WinError(ctypes.get_last_error())
    if ctypes.get_last_error() == ERROR_ALREADY_EXISTS:
        kernel32.CloseHandle(handle)
        raise RuntimeError("Another supervisor instance is already running")
    return handle


def stream_child(pipe: Any, logger: logging.Logger, redactor: SecretRedactor) -> None:
    try:
        for line in iter(pipe.readline, ""):
            clean = redactor.redact(line.rstrip())
            if clean:
                logger.info("tunnel: %s", clean)
    finally:
        pipe.close()


def stop_child(process: subprocess.Popen[str], logger: logging.Logger) -> None:
    if process.poll() is not None:
        return
    logger.info("Stopping tunnel runtime")
    process.terminate()
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        logger.warning("Tunnel runtime did not stop in 10 seconds; killing it")
        process.kill()
        process.wait(timeout=5)


def run(config: dict[str, Any]) -> int:
    secret_path = Path(config["secret_path"])
    secret = load_secret(secret_path)
    logger, redactor = configure_logging(Path(config["log_dir"]), secret)
    state_path = Path(config["state_path"])
    stop_path = Path(config["stop_request_path"])
    stop_event = threading.Event()
    signal.signal(signal.SIGTERM, lambda *_: stop_event.set())
    signal.signal(signal.SIGINT, lambda *_: stop_event.set())
    backoff = float(config.get("backoff_initial_seconds", 2))
    max_backoff = float(config.get("backoff_max_seconds", 60))
    reset_after = float(config.get("backoff_reset_after_seconds", 300))
    restart_count = 0
    job = WindowsJob()
    logger.info("Supervisor started runtime=%s workstation=%s", RUNTIME_ID, WORKSTATION_ID)
    try:
        while not stop_event.is_set():
            if stop_path.exists():
                stop_event.set()
                break
            child_env = os.environ.copy()
            child_env["CONTROL_PLANE_API_KEY"] = secret
            child_env["CONTROL_PLANE_TUNNEL_ID"] = config["tunnel_id"]
            child_env["MCP_COMMAND"] = config["mcp_command"]
            started = time.monotonic()
            process = subprocess.Popen(
                [config["tunnel_client_path"], "run"], env=child_env,
                stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, encoding="utf-8", errors="replace", bufsize=1,
                creationflags=CREATE_NO_WINDOW if os.name == "nt" else 0,
            )
            del child_env
            job.assign(process)
            output_thread = threading.Thread(target=stream_child, args=(process.stdout, logger, redactor), daemon=True)
            output_thread.start()
            logger.info("Tunnel runtime started pid=%d", process.pid)
            failures = 0
            ready = False
            next_health = started + float(config.get("startup_grace_seconds", 20))
            while process.poll() is None and not stop_event.is_set():
                if stop_path.exists():
                    stop_event.set()
                    break
                now = time.monotonic()
                if now >= next_health:
                    result = check_ready(config["ready_url"])
                    ready = result.ready
                    failures = 0 if ready else failures + 1
                    atomic_json(state_path, {
                        "runtime_id": RUNTIME_ID, "workstation_id": WORKSTATION_ID,
                        "supervisor_pid": os.getpid(), "tunnel_pid": process.pid,
                        "status": "ready" if ready else "starting_or_unhealthy",
                        "ready": ready, "health_detail": result.detail,
                        "restart_count": restart_count, "updated_unix": int(time.time()),
                    })
                    if ready:
                        logger.info("Readiness check passed")
                    elif failures >= int(config.get("health_failure_threshold", 6)):
                        logger.warning("Readiness failed %d consecutive times; restarting tunnel", failures)
                        stop_child(process, logger)
                        break
                    next_health = now + float(config.get("health_interval_seconds", 5))
                stop_event.wait(0.5)
            if stop_event.is_set():
                stop_child(process, logger)
                break
            exit_code = process.wait()
            output_thread.join(timeout=2)
            # The tunnel can spawn the MCP bridge. End every descendant before
            # starting a replacement, even when the tunnel parent is already gone.
            job.terminate(exit_code if exit_code else 1)
            runtime_seconds = time.monotonic() - started
            restart_count += 1
            logger.warning("Tunnel runtime exited code=%s after %.1fs; restart in %.1fs", exit_code, runtime_seconds, backoff)
            atomic_json(state_path, {
                "runtime_id": RUNTIME_ID, "workstation_id": WORKSTATION_ID,
                "supervisor_pid": os.getpid(), "tunnel_pid": None, "status": "backoff",
                "ready": False, "last_exit_code": exit_code, "restart_count": restart_count,
                "backoff_seconds": backoff, "updated_unix": int(time.time()),
            })
            if stop_event.wait(backoff):
                break
            backoff = float(config.get("backoff_initial_seconds", 2)) if runtime_seconds >= reset_after else min(max_backoff, backoff * 2)
        atomic_json(state_path, {
            "runtime_id": RUNTIME_ID, "workstation_id": WORKSTATION_ID,
            "supervisor_pid": os.getpid(), "tunnel_pid": None, "status": "stopped",
            "ready": False, "restart_count": restart_count, "updated_unix": int(time.time()),
        })
        logger.info("Supervisor stopped")
        return 0
    finally:
        job.close()
        try:
            stop_path.unlink()
        except FileNotFoundError:
            pass
        secret = ""
        redactor.secret = ""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, type=Path)
    args = parser.parse_args()
    try:
        acquire_single_instance()
        return run(load_config(args.config.resolve()))
    except Exception as exc:
        # No secret values are included in configuration/DPAPI errors produced here.
        print(f"{RUNTIME_ID} failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
